### ISSUE TITLE
Intellihide does not work on 3.16

### ISSUE THREAD

**Issue by jlacson** [ozonos/atom-dock#55]
Title says it all. Running 3.16 on Arch.

Will include link to screencast to demonstrate.

**Comment by cldx** [comment]
Totally confirmed :)

No screencast needed, i know what a static dock looks like ;)

Instead i just leave this here:
```
(gnome-shell:3024): Gjs-WARNING **: JS ERROR: TypeError: (intermediate value).get_outer_rect is not a function
Intellihide<._updateDockVisibility@/usr/share/gnome-shell/extensions/atom-dock@ozonos.org/intellihide.js:237
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
@/usr/share/gnome-shell/extensions/atom-dock@ozonos.org/intellihide.js:188
(gnome-shell:3024): GLib-CRITICAL **: Source ID 39034 was not found when attempting to remove it
(gnome-shell:3024): Gjs-WARNING **: JS ERROR: TypeError: (intermediate value).get_outer_rect is not a function
Intellihide<._updateDockVisibility@/usr/share/gnome-shell/extensions/atom-dock@ozonos.org/intellihide.js:237
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
```

**Comment by micheleg** [comment]
Have a look at this: https://github.com/micheleg/dash-to-dock/commit/3d3eaa4f450a1d49fc641daad162ffc7e87308af .

And you might be interested in this as well: https://github.com/micheleg/dash-to-dock/commit/226234decd0b8665a68b8b87f1962145ccdfe25d .

**Comment by cldx** [comment]
@micheleg  thanks man, you're the best :)

**Comment by cldx** [comment]
Should be fixed in master from #56
